name: aurorafiles
description: File management system for PrivateMail.

versionName: 0.0.6
versionCode: 6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations:

  meta:
  # state management
  mobx:
  flutter_mobx:
  provider:

  # http
  http:

  # local storage
  moor_flutter:
  shared_preferences:
  flutter_secure_storage:
  sqflite:

  # file downloading/uploading
  file_picker:
  #  flutter_uploader: ^1.0.3+1
  #  flutter_downloader: ^1.1.9
  path_provider:
  downloads_path_provider: 0.0.1

  # file encryption
  encrypt:

  # file share
  share_extend:

  # opening files with other apps
  open_file:

  # ui
  material_design_icons_flutter:
  cupertino_icons:
  shimmer:
  cached_network_image:
  percent_indicator:
  flutter_svg:
  #  fluttertoast: 3.0.5

  # misc
  url_launcher:
  filesize:
  intl:
  permission_handler:
  connectivity:
  uuid:

  package_info:

  get_it:

  #async util
  rxdart:

  #crashlytics
  firebase_crashlytics:
  firebase_core:

  crypto_plugin:
    path: crypto_plugin

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.6.5
  mobx_codegen: ^0.3.3+1
  chopper_generator: ^3.0.0
  moor_generator: ^1.6.0+2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/
    - lib/assets/svg/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
