name: aurorafiles
description: File management system for PrivateMail.

versionName: 0.0.6
versionCode: 6

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state management
  mobx: ^0.3.5
  flutter_mobx: ^0.3.0+1
  provider: ^2.0.0

  # http
  http: ^0.12.0+2
  dio: ^3.0.6

  # local storage
  sqflite: 1.1.7+3
  shared_preferences: ^0.5.3+4
  flutter_secure_storage: ^3.2.1+1

  # file downloading/uploading
  file_picker: ^1.3.8
  #  flutter_uploader: ^1.0.3+1
  #  flutter_downloader: ^1.1.9
  path_provider: 1.2.0
  downloads_path_provider: ^0.1.0

  # file encryption
  encrypt: ^3.2.0

  # file share
  share_extend: ^1.0.9

  # opening files with other apps
  open_file: ^2.0.3

  # ui
  mpv: ^0.0.1
  material_design_icons_flutter: ^3.2.4096
  cupertino_icons: ^0.1.2
  shimmer: ^1.0.0
  cached_network_image: ^1.1.1
  percent_indicator: ^2.1.1+1
  flutter_svg: ^0.14.4
  #  fluttertoast: 3.0.5

  # misc
  url_launcher: ^5.1.2
  filesize: ^1.0.4
  intl: ^0.15.8
  permission_handler: ^3.3.0
  connectivity: ^0.4.4
  uuid: ^2.0.2

  # di
  async_injector: ^0.1.2+2

  # async util
  rxdart: ^0.22.6

  crypto_plugin:
    path: crypto_plugin

  domain:
    path: domain
  domain_impl:
    path: domain_impl

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.6.5
  mobx_codegen: ^0.3.3+1
  chopper_generator: ^3.0.0
  moor_generator: ^1.6.0+2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - res/images/
    - res/svg/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
