name: aurorafiles
description: File management system for ...
publish_to: none

version: 2.4.0+162

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  secure_sharing:
    path: module/secure_sharing/secure_sharing
  secure_sharing_impl:
    path: module/secure_sharing/secure_sharing_impl

  flutter_cupertino_localizations:

  meta:
  # state management
  mobx:
  flutter_mobx:
  provider:

  # http
  http:

  # local storage`
  moor_flutter:
  shared_preferences: 0.5.6+3
  flutter_secure_storage: 4.2.1
  sqflite:

  # file downloading/uploading+
  file_picker: ^4.0.0
  #  flutter_uploader: ^1.0.3+1
  #  flutter_downloader: ^1.1.9
  path_provider:

  # file encryption
  encrypt:

  # file share
  share: 0.6.5+4

  # opening files with other apps
  open_file: ^3.2.1

  # ui
  flutter_keyboard_visibility: ^5.0.3
  material_design_icons_flutter:
  cupertino_icons:
  shimmer:
  cached_network_image:
  percent_indicator: 3.0.1
  flutter_svg: 0.21.0
  #  fluttertoast: 3.0.5
  dropdown_search: 2.0.1

  # misc
  url_launcher: ^6.0.9
  filesize:
  intl:
  permission_handler: 3.3.0
  connectivity:
  uuid:
  uni_links: 0.4.0
  package_info:
  device_info_plus: ^2.1.0
  get_it:

  #async util
  rxdart:

  #crashlytics
  firebase_crashlytics: 2.2.1

  theme:
    path: build_res/afterlogic/theme
  aurora_ui_kit:
    git: https://github.com/afterlogic/aurora_ui_kit_flutter.git
  crypto_stream:
    git:
      url: https://github.com/afterlogic/flutter_crypto_stream
      ref: pgp_without_public_key
  receive_sharing:
    git: https://github.com/afterlogic/receive_sharing
  # fido
  yubico_flutter:
    path: module/mocks/yubico_flutter

  # logger
  aurora_logger:
    git: https://github.com/afterlogic/aurora_logger_flutter

  flutter_bloc: 3.2.0
  flutter_custom_tabs: 1.0.2
  equatable: 1.1.1

dependency_overrides:
  yaml: ^2.1.15
  dart_style: ^1.0.0
  image: ^2.1.1
  xml: ^4.2.0
  firebase_crashlytics_platform_interface: 3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  localizator: 0.1.0+2
  build_runner: ^1.6.5
  mobx_codegen: ^0.3.3+1
  chopper_generator: ^3.0.0
  moor_generator: ^1.6.0+2
  build_variant:
    git: "https://github.com/afterlogic/build_variant"
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  ios: true
  android: true
  image_path: build_res/afterlogic/image/icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: build_res/afterlogic/image/icon_foreground.png

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/
    - lib/assets/svg/
    - build_res/afterlogic/image/icon.png
    - build_res/afterlogic/image/main_logo.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



