name: aurorafiles
description: File management system for ...
publish_to: none

version: 2.3.1+161

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  secure_sharing:
    path: module/secure_sharing/secure_sharing
  secure_sharing_impl:
    path: module/secure_sharing/secure_sharing_impl

  meta: ^1.7.0
  # state management
  mobx: ^2.0.7
  flutter_mobx: ^2.0.6+1
  provider: ^6.0.3

  # http
  http: ^0.13.5

  # local storage`
  moor_flutter: ^4.1.0
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^5.0.2
  sqflite: ^2.0.2+1

  # file downloading/uploading+
  file_picker: ^4.6.1
  #  flutter_uploader: ^1.0.3+1
  #  flutter_downloader: ^1.1.9
  path_provider: ^2.0.11

  # file encryption
  encrypt: ^5.0.1

  # file share
  share: ^2.0.4

  # opening files with other apps
  open_file: ^3.2.1

  # ui
  flutter_keyboard_visibility: ^5.3.0
  material_design_icons_flutter: ^5.0.6996
  cupertino_icons: ^1.0.5
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  percent_indicator: ^4.2.1
  flutter_svg: ^1.0.3
  #  fluttertoast: 3.0.5
  dropdown_search: ^3.0.1

  # misc
  url_launcher: ^6.1.5
  filesize: ^2.0.1
  intl: ^0.17.0
  permission_handler: ^10.0.0
  connectivity: ^3.0.6
  uuid: ^3.0.6
  uni_links: ^0.5.1
  package_info: ^2.0.2
  device_info_plus: ^4.0.0
  get_it: ^7.2.0

  #async util
  rxdart: ^0.27.5

  #crashlytics
  firebase_crashlytics: ^2.8.6

  theme:
    path: build_res/afterlogic/theme
  aurora_ui_kit:
    git: https://github.com/afterlogic/aurora_ui_kit_flutter.git
  crypto_stream:
    git:
      url: https://github.com/afterlogic/flutter_crypto_stream
      ref: flutter_2.10

  receive_sharing_intent: ^1.4.5

  # fido
  yubico_flutter:
    path: module/mocks/yubico_flutter

  # logger
  aurora_logger:
    git: https://github.com/afterlogic/aurora_logger_flutter

  flutter_bloc: 7.3.3
  flutter_custom_tabs: ^1.0.4
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  localizator:
    path: ../localizator
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7
  chopper_generator: ^4.0.5
  moor_generator: ^4.6.0+1
  build_variant:
    path: ../build_variant
#    git: "https://github.com/afterlogic/build_variant"
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  ios: true
  android: true
  image_path: build_res/afterlogic/image/icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: build_res/afterlogic/image/icon_foreground.png

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/
    - lib/assets/svg/
    - build_res/afterlogic/image/icon.png
    - build_res/afterlogic/image/main_logo.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



