name: secure_sharing_impl
description: A new Flutter package.
publish_to: none
version: 0.0.3

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  drift_sqflite: ^2.0.0

  aurorafiles:
    path: ../../..
  crypto_stream:
    git:
      url: https://github.com/afterlogic/flutter_crypto_stream
      ref: flutter_3.3
  secure_sharing:
    path: ../secure_sharing
  aurora_ui_kit:
    git: https://github.com/afterlogic/aurora_ui_kit_flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter
