name: secure_sharing_impl
description: A new Flutter package.
version: 0.0.2
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  aurorafiles:
    path: ../../..
  crypto_stream:
    git:
      url: https://github.com/afterlogic/flutter_crypto_stream
      ref: flutter_2.10
#      ref: master
  secure_sharing:
    path: ../secure_sharing
  aurora_ui_kit:
    git: https://github.com/afterlogic/aurora_ui_kit_flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
