name: yubico_flutter
description: A new Flutter package.
publish_to: none
version: 0.0.3

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
